### ISSUE TITLE
move events to their own object on the client class

### ISSUE THREAD

**Issue by fox-cat** [fox-cat/coward#17]
move the events to a separate object on the client class? (as opposed to just having them exist as `evtFooBar`... instead `evt.fooBar`)

this would allow to keep the Client file more maintainable, however it has the downside of the user-side code reading like
`client.evt.ready.attach(...`
and im not sure how i feel about that

could keep it the way it is now, but it also makes the documentation cluttered (having a bunch of functions/objects on the client class makes the docs a pain to scroll through...)

**Comment by fox-cat** [comment]
this would also allow users to do
```ts
const events = client.evt
events.ready.attach(...
```
or something of that nature, which is kind of nice as well

**Comment by userterminal** [comment]
I agree with what you say here but how do you think you'll implement it?

**Comment by fox-cat** [comment]
separate file with all the event declarations, and (pseudo code here)
`import events from "file"`
`this.evt = events`

**Comment by fox-cat** [comment]
done in #24
