### ISSUE TITLE
DM channel doesn't return anything.

### ISSUE THREAD

**Issue by nougator** [fox-cat/coward#23]
**Describe the bug**
DM channel doesn't return anything.

**To Reproduce**
1. Just by trying to get the channel type when someone send a DM to the bot.
4. See error.

**Expected behavior**
Should return 1.

**Additional context**
I'm using javascript not typescript.

**Comment by fox-cat** [comment]
odd.. don't know why this happens. i'll look into it!

**Comment by fox-cat** [comment]
alright i know why this happens lol
