### ISSUE TITLE
Some text channel classes cannot send such as embed message

### ISSUE THREAD

**Issue by MikuroXina** [fox-cat/coward#29]
**Describe the bug**
`send` method of DMChannel, GuildTextChannel, and so on takes only `string` argument.
I wanted to send an embed message but not supported.
`Client.postMessage` can send embed message because it takes `string | Options.postMessage`.

**To Reproduce**
1. Call their `send` method by embed message object.

**Expected behavior**
`send` method of DMChannel, GuildTextChannel, and so on should takes `string | Options.postMessage` argument.

**Additional context**
As a first aid, just casting `Options.postMessage` object to `string`, it looks worked well now.

```ts
(mes: Options.postMessage) => {
  dm.send((mes as unknown) as string);
}
```

(I'm Japanese so my English may be bad, sorry.)

**Comment by fox-cat** [comment]
hey! i believe this is fixed on the [dev branch], however the method names are different ^^;;

(`<TextChannel>.send` has been changed to `<TextChannel>.createMessage`), and (`<Client>.postMessage` has been changed to `<Client>.createMessage`)

[dev branch]: https://github.com/fox-cat/coward/tree/dev

**Comment by MikuroXina** [comment]
Thank you for replying, I just checked it.
Do i need to keep open this issue until it's resolved?

**Comment by fox-cat** [comment]
sorry for the delayed response!
the issue has been resolved
