### ISSUE TITLE
modifyChannel return status 400

### ISSUE THREAD

**Issue by Joralmo** [fox-cat/coward#4]
**Describe the bug**
i have a channel type 0

**To Reproduce**
1. make client.modifyChannel(id, { type: 2 });

**Expected behavior**
Return error message
**Screenshots**
messaje and status code response

![image](https://user-images.githubusercontent.com/19753876/81638213-04c0fa00-93de-11ea-8faa-93878faf9134.png)

**Comment by fox-cat** [comment]
hello,
is the issue that it doesn't error out?

**Comment by fox-cat** [comment]
@all-contributors please add @Joralmo for bugs, thanks
