### ISSUE TITLE
Error in GUILD_MEMBER_REMOVE case

### ISSUE THREAD

**Issue by Joralmo** [fox-cat/coward#8]
**Describe the bug**
I removed a member from a channel and received an error shown in screenshot below

**To Reproduce**
1. Delete a member of channel

**Expected behavior**
be able to emit guildMemberRemove

**Screenshots**
![image](https://user-images.githubusercontent.com/19753876/81893342-1982c680-9573-11ea-9c89-7086831fd54a.png)

**Comment by fox-cat** [comment]
please let me know if this issue is truely fixed or not

**Comment by Joralmo** [comment]
Let me try after I'm on the pc

**Comment by Joralmo** [comment]
I have tried again and the error has not come out! brilliant
@fox-cat
